CREATE TABLE DEPARTMENT_TBL (
DEPT_NO VARCHAR2(15 BYTE) NOT NULL PRIMARY KEY,
DEPT_NAME VARCHAR2(30 BYTE) NULL,
DEPT_LOCATION VARCHAR2(50 BYTE) NULL
);

CREATE TABLE EMPLOYEE_TBL (
EMP_NO     NUMBER             NOT NULL PRIMARY KEY,
DEPT_NO    VARCHAR2(15 BYTE)  REFERENCES DEPARTMENT_TBL(DEPT_NO) ON DELETE SET NULL,
POSITION   CHAR(10 BYTE)      NULL,
NAME       VARCHAR2(15 BYTE)  NULL,
HIRE_DATE  DATE               NULL,
SALARY     NUMBER             NULL
);

CREATE TABLE PROJECT_TBL (
PJT_NO     NUMBER             NOT NULL PRIMARY KEY,
PJT_NAME   VARCHAR2(30 BYTE)  NULL,
BEGIN_DATE DATE               NULL,
END_DATED  DATE               NULL
);

CREATE TABLE PROCEEDING_TBL (
PCD_NO     NUMBER NOT NULL PRIMARY KEY,
EMP_NO     NUMBER REFERENCES EMPLOYEE_TBL(EMP_NO) ON DELETE SET CASCADE,
PJT_NO     NUMBER REFERENCES PROJECT_TBL(PJT_NO)  ON DELETE SET NULL,
PJT_STATE  NUMBER NOT NULL
);

DROP TABLE PROCEEDING_TBL;
DROP TABLE PROJECT_TBL;
DROP TABLE EMPLOYEE_TBL;
DROP TABLE DEPARTMENT_TBL;
